# Generated by Django 4.1.7 on 2023-04-03 16:22

import django.core.validators
from django.db import migrations, models
import imdb_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birth_year',
            field=models.IntegerField(db_column='birth_year', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(db_column='year', validators=[django.core.validators.MinValueValidator(1800), imdb_app.models.validate_year_before_now]),
        ),
    ]
