# Generated by Django 4.1.7 on 2023-04-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0002_alter_actor_birth_year_alter_movie_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieactor',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
